config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' } do
    match '/users/sessions', to: 'users/sessions#options', via: :options

    end

  devise_scope :user do
    delete 'delete_account/:id', to: 'users/registrations#delete_account', as: 'delete_account_user'
    get 'users/sign_out', to: 'users/sessions#destroy'
  end

  namespace :api do
    resources :photos do
      resources :comments, only: [:index, :create, :destroy]
    end
    resources :users, only: [:index, :show, :update] do
      member do
        post 'update_photo', to: 'users#update_photo'
      end
      get 'following_status', to: 'users#following_status', as: 'following_status' # New route to check follow status
      get 'following', to: 'users#following' # New route to fetch following users
      member do
        post :follow
        post :unfollow
        get :followers
        get :relationships
      end
      collection do
        get 'search', to: 'users#search' # Adding the search route here
      end
    end

    devise_for :users, controllers: {
      sessions: 'api/sessions',
      registrations: 'api/registrations'
    }
    
    devise_scope :user do
      get 'sessions/current', to: 'sessions#current'
      post 'sessions' => 'sessions#create'
      get 'sessions' => 'sessions#show'
      delete 'sessions' => 'sessions#destroy'
      post 'users' => 'registrations#create'
      post 'change-password', to: 'registrations#change_password'
      post 'registrations', to: 'registrations#create'
    end
    
    resources :post_subscriptions
    resources :subscriptions
    resources :articles do
      collection do
        get 'user_articles', to: 'articles#user_articles'
      end
      resources :comments
    end
    resources :sessions, only: [:create, :destroy]
    resources :registrations, only: [:create, :destroy]
  end
  
  resources :subscriptions, only: [:create, :destroy]
  resources :post_subscriptions, only: [:create, :destroy]
  root "articles#index"
end

app/models/article.rb
class Article < ApplicationRecord
  # include Visible

  has_many :comments, dependent: :destroy
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true

  has_one_attached :photo

  has_many :post_subscriptions, dependent: :destroy
  has_many :subscribers, through: :post_subscriptions, source: :user
  def photo_url
    if photo.attached?
      url = Rails.application.routes.url_helpers.rails_blob_url(photo, only_path: true)
      puts "Photo URL: #{url}" # Debugging line to check the URL
      return url
    else
      puts "No photo attached." # Debugging line to indicate no photo is attached
      return nil
    end
  end
  def user_photo_url
    user.photo_url if user.present?
  end
  def self.ransackable_attributes(auth_object = nil)
    %w[title body]
  end
end

app/controllers/api/articles_controller.rb
class Api::ArticlesController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @articles = Article.includes(:user).all
    render json: @articles.as_json(include: { 
      user: { only: [:id, :name, :nickname, :photo] },
      comments: { only: [:id, :body, :created_at, :commenter] } }, 
      methods: [:photo_url, :user_photo_url])
  end

  def user_articles
    if params[:user_id].present?
      @articles = Article.includes(:user).where(user_id: params[:user_id])
      render json: @articles.as_json(include: { user: { only: [:id, :name, :nickname, :photo] }, comments: { only: [:id, :body, :created_at, :commenter] } }, methods: [:photo_url])
    else
      render json: { error: "User ID is required" }, status: :bad_request
    end
  end

  def show
    @article = Article.find(params[:id])
    render json: @article.as_json(include: { 
      user: { 
        only: [:id, :name, :nickname] 
      } 
    }).merge({
      photo: @article.user.photo.attached? ? url_for(@article.user.photo) : nil,
      comments: @article.comments.as_json(only: [:id, :body, :created_at, :commenter])
    })
  rescue ActiveRecord::RecordNotFound
    render json: { error: 'Статья не найдена' }, status: :not_found
  end

  def create
    puts "Received parameters: #{params.inspect}"

    if params[:user_id].blank?
      render json: { error: "User ID is required" }, status: :bad_request
      return
    end

    @user = User.find_by(id: params[:user_id])
    if @user.nil?
      render json: { error: "User not found" }, status: :not_found
      return
    end

    @article = @user.articles.new(article_params)
    puts "Article params before save: #{@article.attributes.inspect}"
    @article.photo.attach(params[:article][:photo]) if params[:article][:photo].present?

    @article.status = 'Default_status'
    puts "Article before save: #{@article.attributes.inspect}"
    if @article.save
      render json: @article.as_json(methods: [:photo_url]), status: :created
    else
      logger.error("Article creation failed: #{@article.errors.full_messages.join(', ')}")
      render json: { error: "НЕТ ЗАПИСЕЙ" }
    end
  end

  def update
    puts "Received parameters: #{params.inspect}"
    @article = Article.find(params[:id])
    if @article.update(article_params)
      render json: @article.as_json(methods: [:photo_url]), status: :ok
    else
      render json: { error: "НЕТ ЗАПИСЕЙ"}
    end
  end

  def destroy
    if params[:id].present?
      @article = Article.find(params[:id])
      PostSubscription.where(article_id: @article.id).destroy_all
      @article.destroy
      render json: { message: "Статья удалена" }, status: :ok
    else
      render json: { error: "Не указан идентификатор статьи" }, status: :bad_request
    end
  rescue ActiveRecord::RecordNotFound
    render json: { error: "Статья не найдена" }, status: :not_found
  end

  private

  def article_params
    params.require(:article).permit(:title, :body, :status, :photo)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
    @q = Article.ransack(params[:q])
    @articles = @q.result(distinct: true)
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.build(article_params)
    puts "Attempting to save article with photo: #{@article.photo.attached?}" # Debugging line
    if @article.save
      redirect_to @article, notice: 'Article was successfully created.'
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    puts "Attempting to update article with photo: #{@article.photo.attached?}" # Debugging line
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def article_params
      params.require(:article).permit(:title, :body, :status, :photo)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: @article, local: true) do |form| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>
      <ul>
        <% @article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, "Заголовок" %>
    <%= form.text_field :title, id: :article_title %>
  </div>

  <div class="field">
    <%= form.label :body, "Текст" %>
    <%= form.text_area :body, id: :article_body %>
  </div>

  <div class="field">
    <%= form.label :photo, "Ваша бомбезная фоточка" %>
    <%= form.file_field :photo, id: :article_photo %>
  </div>

  <div class="actions">
    <%= form.submit "Сохранить" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Посты</h1>

<%= search_form_for @q, url: api_articles_path do |f| %>
  <div class="field">
    <%= f.label :title_cont, "Название поста" %>
    <%= f.search_field :title_cont %>
  </div>
  <div class="field">
    <%= f.label :body_cont, "Содержание поста" %>
    <%= f.search_field :body_cont %>
  </div>
  <div class="actions">
    <%= f.submit "Поиск" %>
  </div>
<% end %>


<ul>
  <li>
<%= link_to 'All Articles', api_articles_path %>
  <% @articles.each do |article| %>
      <li>
      <% if article.photo.attached? %>
<%= link_to(api_article_path(article)) do %>
        <%= image_tag(article.photo.variant(resize_to_limit: [300, 100])) %>
        <span><%= article.title %></span>
<% end %>
      <% else %>
<%= link_to article.title, api_article_path(article) %>
      <% end %>
      </li>
  <% end %>
</ul>

app/views/articles/new.html.erb
<h1>Ваш новый крутой пост!</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<% if @article&.photo.present? %>
<%= image_tag @article.photo.variant(resize_to_limit: [400, 400]), class: "article-photo" %>
<% end %>
<p><%= @article.body %></p>



<% if @article.user.id == current_user.id %>
<ul>
  <li><%= link_to "Редактировать", edit_article_path(@article) %></li>
  <li><%= link_to "Удалить", article_path(@article), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Вы уверены?"
                  } %></li>
</ul>
<% end %>

<% if user_signed_in? && !current_user.subscribed_posts.include?(@article) && @article.user.id != current_user.id%>
  <%= button_to 'Подписаться на пост', post_subscriptions_path(post_id: @article.id), method: :post %>
<% elsif user_signed_in? && @article.user.id != current_user.id %>
  <%= button_to 'Отписаться от поста', post_subscription_path(@article), method: :delete %>
<% end %>



<h2>Comments</h2>
<%= render @article.comments if false %>

<h2>Add a comment:</h2>
 <%= render "comments/form", article: @article if false %>