config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' } do
    match '/users/sessions', to: 'users/sessions#options', via: :options

    end

  devise_scope :user do
    delete 'delete_account/:id', to: 'users/registrations#delete_account', as: 'delete_account_user'
    get 'users/sign_out', to: 'users/sessions#destroy'
  end

  namespace :api do
    resources :photos do
      resources :comments, only: [:index, :create, :destroy]
    end
    resources :users, only: [:index, :show, :update] do
      member do
        post 'update_photo', to: 'users#update_photo'
      end
      get 'following_status', to: 'users#following_status', as: 'following_status' # New route to check follow status
      get 'following', to: 'users#following' # New route to fetch following users
      member do
        post :follow
        post :unfollow
        get :followers
        get :relationships
      end
      collection do
        get 'search', to: 'users#search' # Adding the search route here
      end
    end

    devise_for :users, controllers: {
      sessions: 'api/sessions',
      registrations: 'api/registrations'
    }
    
    devise_scope :user do
      get 'sessions/current', to: 'sessions#current'
      post 'sessions' => 'sessions#create'
      get 'sessions' => 'sessions#show'
      delete 'sessions' => 'sessions#destroy'
      post 'users' => 'registrations#create'
      post 'change-password', to: 'registrations#change_password'
      post 'registrations', to: 'registrations#create'
    end
    
    resources :post_subscriptions
    resources :subscriptions
    resources :articles do
      collection do
        get 'user_articles', to: 'articles#user_articles'
      end
      resources :comments
    end
    resources :sessions, only: [:create, :destroy]
    resources :registrations, only: [:create, :destroy]
  end
  
  resources :subscriptions, only: [:create, :destroy]
  resources :post_subscriptions, only: [:create, :destroy]
  root "articles#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

  <%= javascript_include_tag 'https://code.jquery.com/jquery-3.3.1.slim.min.js',
integrity: 'sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo',
crossorigin: 'anonymous' %>
<%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js',
integrity: 'sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl',
crossorigin: 'anonymous' %>
    <title><%= content_for(:title) || "Gramchik" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css',
    integrity: 'sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO',
    crossorigin: 'anonymous', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://use.fontawesome.com/releases/v5.4.1/css/all.css',
    integrity: 'sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz',
    crossorigin: 'anonymous', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<div>

</div>
    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
  </head>

  <body>
  <script>
$(document).ready(function(){
    $('.dropdown-toggle').dropdown();
});
</script>
  <nav class="navbar navbar-light sticky-top bg-light">
  <%= link_to "<i class='fab fa-instagram'></i> Gramchik".html_safe, root_path, class: "navbar-brand" %>
      <ul class="nav">
          <% if user_signed_in? %>
          <li class="nav-item">
<%= button_to "Создать пост", new_api_article_path, method: :get,
              class: "btn btn-primary btn-md btn-success", data: { toggle: "modal" } %>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user&.photo.present? %>
              <%= image_tag current_user.photo.variant(resize_to_limit: [50, 50]), class: "profile-photo" %>
          <% end %>
            <li><%= link_to "Мой профиль", edit_user_registration_path %></li>
            <li><%= link_to "Выйти", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Регистрация", new_user_registration_path %></li>
            <li><%= link_to "Войти", new_user_session_path %></li>
          <% end %>
          </ul>
      </ul>
  </nav>

  <main class="container" style="min-height: 500px;">
    <%= yield %>
  </main>
  <footer class="navbar navbar-expand-lg footer-custom">
  <div class="container">
    <nav class="navbar-nav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <span class="nav-link font-size-sm">&copy; Ruby и точка 2024</span>
        </li>
      </ul>
    </nav>
  </div>
</footer>
  </body>
</html>